driver: str = '{SQL Server}'
server: str = '(local)\SQLEXPRESS'
uid_file_path: str = 'C:\\Windows\\System32\\drivers\\etc\\secrets\\umbracoDBuid.txt'
pwd_file_path: str = 'C:\\Windows\\System32\\drivers\\etc\\secrets\\umbracoDBpwd.txt'
database: str = 'DanceManagementUmbraco'
trusted_connection: str = 'yes'